### ISSUE TITLE
date tests not localised correctly

### ISSUE THREAD

**Issue by alxndrsn** [medic/medic-api#29] opened 2015-08-17 05:38 UTC
Passes fine on Travis, so I assume this is a localisation/timezone issue.

Test output:
```javascript
Testing missing-delivery-reports.js...F
>> get returns all registrations with missed delivery reports
>> Error: '1969-12-31T23:00:00.000Z' == '1970-01-01T00:00:00.000Z'
>> at /Users/user/workspaces/medic/api/tests/controllers/missing-delivery-reports.js:156:10
>> at /Users/user/workspaces/medic/api/controllers/utils.js:262:7
>> at /Users/user/workspaces/medic/api/node_modules/async/lib/async.js:377:13
>> at /Users/user/workspaces/medic/api/node_modules/async/lib/async.js:52:16
>> at /Users/user/workspaces/medic/api/node_modules/async/lib/async.js:267:32
>> at /Users/user/workspaces/medic/api/node_modules/async/lib/async.js:44:16
>> at /Users/user/workspaces/medic/api/node_modules/async/lib/async.js:374:17
>> at /Users/user/workspaces/medic/api/controllers/utils.js:55:9
>> at /Users/user/workspaces/medic/api/controllers/utils.js:34:5

Testing monthly-registrations.js..OK
Testing monthly-deliveries.js...OK
Testing records.js.........OK
Testing total-births.js...OK
Testing upcoming-appointments.js.......OK
Testing upcoming-due-dates.js...F
>> get returns all women with upcoming due dates
>> Error: '1969-12-31T23:00:00.000Z' == '1970-01-01T00:00:00.000Z'
>> at /Users/user/workspaces/medic/api/tests/controllers/upcoming-due-dates.js:158:10
>> at /Users/user/workspaces/medic/api/controllers/utils.js:262:7
>> at /Users/user/workspaces/medic/api/node_modules/async/lib/async.js:377:13
>> at /Users/user/workspaces/medic/api/node_modules/async/lib/async.js:52:16
>> at /Users/user/workspaces/medic/api/node_modules/async/lib/async.js:267:32
>> at /Users/user/workspaces/medic/api/node_modules/async/lib/async.js:44:16
>> at /Users/user/workspaces/medic/api/node_modules/async/lib/async.js:374:17
>> at /Users/user/workspaces/medic/api/controllers/utils.js:55:9
>> at /Users/user/workspaces/medic/api/controllers/utils.js:34:5
```

**Comment by garethbowen** [comment] 2015-08-17 07:51
@alxndrsn Have you checked out this commit from earlier today: https://github.com/medic/medic-api/commit/f9e0eb473e080608c34d4f9620f2ce620fefc8b6 ? Was it broken before you applied this change, or just after?

**Comment by alxndrsn** [comment] 2015-08-17 09:24
```bash
$ git log --pretty=oneline | head -n3
2ba960af4b5317d63d3d0d3a1865654914225a9e Added api documentation for exporting messages, reports, audit logs, and user feedback
ee9ecf2b8e98569aac309f8c68b8eaa33e4a9234 Fix messages url
f9e0eb473e080608c34d4f9620f2ce620fefc8b6 Test pass locally mostly by setting tz to utc. Issue: #12
```

**Comment by garethbowen** [comment] 2015-08-17 20:07
Right, so fixing that failure in my timezone caused it in yours. Brilliant. It seems to be related to DST. At had a test which proved that  `moment().subtract(40, 'weeks').add(40, 'weeks')` was not equal to `moment()`. Good times.

**Comment by garethbowen** [comment] 2015-08-17 23:43
I'm calling this a duplicate of #12

**Closed by garethbowen** 2015-08-17 23:43 UTC
Labels: bug
