### ISSUE TITLE
handle migration failure better

### ISSUE THREAD

**Issue by mandric** [medic/medic-api#52] opened 2016-03-18 21:50 UTC
I got stuck recently because `extract-user-settings` migration was failing and that keeps the other migrations from running.  But it wasn't clear there was something seriously wrong other than an error in the log, medic-api continued functioning normally (serving requests).  It might be better to kill the process if migrations fail so migrations can re-run/might not fail subsequently and the admin would know the data migrations need to be fixed before the app can function normally.   Adding a `process.exit(1)` on this line when the `migrations.run` fails might be the right fix. https://github.com/medic/medic-api/blob/develop/server.js#L510

The `extact-user-settings` migration was failing with 409 because my dev database already had those docs.

**Comment by mandric** [comment] 2016-04-15 17:46
I ran into this again when migration "extract-user-settings" failed with "roles is a required array" because `validate_doc_update` now requires a `roles` property on all user-settings docs.  I feel like medic-api should fail (not start serving requests) until the migrations can run because if one migration fails all migration fail, essentially the database is not consistent. I'd prefer medic-api fail to start until migrations complete successfully. Opinions?

**Comment by estellecomment** [comment] 2016-06-08 14:10
Half-way migrations sound bad, I agree with that.

**Comment by mandric** [comment] 2016-06-08 22:29
@garethbowen here is an example of medic-api in an unhandle-able state where I think a hard crash or exit is the right thing.

**Comment by garethbowen** [comment] 2016-06-08 22:31
An alternative is to not start serving requests until migrations have completed successfully. This is quite brutal but in some cases having not-yet-finished or failed-to-run migrations might cause bugs when using the updated webapp.

**Comment by estellecomment** [comment] 2016-06-14 07:34
There's probably different levels of severity for migration fails, depending on the migration. We could have blocking vs. non-blocking migrations. 

For instance `separate-audit-db.js`, if that fails the system can still run, and we can continue migrating later. Or `convert-bad-dob-format.js`, that's fixing a problem that already exists, if it exists a little longer it's not a big deal.

At the other end, when upgrading a .4 system, you can afford to shut down the instance until the migrations succeed, because anyway if they don't your system will be badly broken. E.g. `extract-person-contacts.js`, `extra-user-settings.js`

Also, one of @mandric's original problems was a migration failing because it had already run. We should make all migrations idempotent (stand back, I'm going to try math) : if they've run already, running them again is a no-op. Will be useful for rerunning a half-run migration, which you'll do when migration fails half-way.

**Comment by garethbowen** [comment] 2016-08-01 00:36
Closed as a duplicate of https://github.com/medic/medic-webapp/issues/2456

**Closed by garethbowen** 2016-08-01 00:36 UTC
